<?php

namespace App\Modules\Blog;

use Carbon\Laravel\ServiceProvider;

class BlogServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->loadRoutesFrom(__DIR__ . '/Routes/web.php');
        $this->loadMigrationsFrom(__DIR__ . '/DataBase/Migrations');
        $this->mergeConfigFrom(__DIR__ . '/Config/blog.php', 'blog');
        $this->loadViewsFrom(__DIR__ . '/Resources/Views','blog');
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
